name: Testing & Deployment

# Only deploy on main branch pushes
on:
  push:
    branches: [ "main" ]

  # Enable manual runs if desired
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest copy of the repository
      - name: Checkout
        uses: actions/checkout@v2.7.0
      # Install NodeJS (for dependencies + running the test)
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install Custom Functions dependencies (if needed)
      - name: Install dependencies
        run: cd unit-testing-custom-functions/custom_functions && yarn && cd ..
      # Run the test script to run the test suites
      - name: Unit Test Custom Functions
        run: cd testing && yarn && yarn test && cd ..
      # Deploy the Custom Functions to our pre-configured Instance
      - name: Deploy Custom Functions
        uses: makvoid/deploy-harperdb-cf-action@main
        with:
          admin_username: ${{ secrets.HDB_ADMIN_USERNAME }}
          admin_password: ${{ secrets.HDB_ADMIN_PASSWORD }}
          hdb_endpoint: ${{ secrets.HDB_ENDPOINT }}
          project_name: ${{ secrets.HDB_PROJECT }}
          cf_directory: 'unit-testing-custom-functions/custom_functions'
          reject_unauthorized_certs: 'false'
